# ─── Stage 1: Build the Mantine / React UI assets ────────────────────────────
# Requires Node >= 22 per upstream Prometheus 3.5 README.
FROM node:22-alpine AS ui-builder

# Install git so we can fetch the mantine-ui / codemirror-promql workspace sources.
RUN apk add --no-cache git bash

# Clone only the web/ui subtree from our prometheus fork at the exact commit
# that matches the vendor directory, then overlay it onto the vendored files.
ARG PROM_FORK_COMMIT=99c77ced4af144e00fa060f2623a2bc4026e0f50

WORKDIR /build/prom-src
RUN git clone --depth=1 --branch release-3.5_fork_promxy \
      https://github.com/jacksontj/prometheus.git . && \
    git checkout ${PROM_FORK_COMMIT} 2>/dev/null || true

# The workspace root we care about is web/ui.
WORKDIR /build/webui

# Copy the vendored package.json + package-lock.json (contain dependency pins).
COPY vendor/github.com/prometheus/prometheus/web/ui/package.json .
COPY vendor/github.com/prometheus/prometheus/web/ui/package-lock.json .
COPY vendor/github.com/prometheus/prometheus/web/ui/build_ui.sh .

# Bring in the workspace packages from the upstream clone.
# These are NOT committed to vendor because they're gitignored upstream.
RUN cp -r /build/prom-src/web/ui/mantine-ui ./mantine-ui
RUN cp -r /build/prom-src/web/ui/module     ./module

# Install workspace dependencies.  Use --legacy-peer-deps to silence any
# peer-dep conflicts introduced by mixing React 19 + older plugin versions.
RUN npm install --legacy-peer-deps

# Build lezer-promql + codemirror-promql modules, then the Mantine UI.
# We skip react-app (old UI) — it requires react-scripts which is not part of
# the workspace and takes ~3 min extra to install for no benefit.
RUN bash build_ui.sh --build-module
RUN npm run build -w @prometheus-io/mantine-ui && \
    mkdir -p static && \
    rm -rf static/mantine-ui && \
    mv mantine-ui/dist static/mantine-ui

# Generate the real embed.go that embeds static/.
# This replaces embed_stub.go (which only embeds README.md) when the Go
# compiler processes the builtinassets tag.
RUN printf '%s\n' \
  '// Code generated by Dockerfile ui-builder stage. DO NOT EDIT.' \
  '//' \
  '//go:build builtinassets' \
  '// +build builtinassets' \
  '' \
  'package ui' \
  '' \
  'import "embed"' \
  '' \
  '//go:embed static' \
  'var EmbedFS embed.FS' \
  > embed.go

# ─── Stage 2: Build the Go binary ─────────────────────────────────────────────
FROM --platform=$BUILDPLATFORM golang:1.24-alpine3.21 AS builder

ARG BUILDPLATFORM
ARG TARGETARCH
ARG TARGETOS
ENV GOARCH=${TARGETARCH} GOOS=${TARGETOS}

COPY . /go/src/github.com/jacksontj/promxy

# Overlay the built UI assets into the vendor tree.
# Replace embed_stub.go with our real embed.go (they both declare EmbedFS under
# the builtinassets tag, so only one may exist at compile time).
COPY --from=ui-builder /build/webui/static \
     /go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/ui/static

COPY --from=ui-builder /build/webui/embed.go \
     /go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/ui/embed.go

RUN rm /go/src/github.com/jacksontj/promxy/vendor/github.com/prometheus/prometheus/web/ui/embed_stub.go

RUN cd /go/src/github.com/jacksontj/promxy/cmd/promxy && CGO_ENABLED=0 go build -mod=vendor -tags netgo,builtinassets
RUN cd /go/src/github.com/jacksontj/promxy/cmd/remote_write_exporter && CGO_ENABLED=0 go build -mod=vendor

# ─── Final image ──────────────────────────────────────────────────────────────
FROM   alpine:3.21.3
LABEL  org.opencontainers.image.authors="Thomas Jackson <jacksontj.89@gmail.com>"
EXPOSE 8082

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/jacksontj/promxy/cmd/promxy/promxy /bin/promxy
COPY --from=builder /go/src/github.com/jacksontj/promxy/cmd/remote_write_exporter/remote_write_exporter /bin/remote_write_exporter

USER       nobody

ENTRYPOINT [ "/bin/promxy" ]
