# syntax=docker/dockerfile:1

# ── Stage 1: Build Mantine/React UI ──────────────────────────────────────────
FROM node:22-alpine AS ui-builder

RUN apk add --no-cache git bash

ARG PROM_FORK_COMMIT=99c77ced4af144e00fa060f2623a2bc4026e0f50

WORKDIR /build/webui

# Copy vendored npm manifests and build script.
COPY vendor/github.com/prometheus/prometheus/web/ui/package.json .
COPY vendor/github.com/prometheus/prometheus/web/ui/package-lock.json .
COPY vendor/github.com/prometheus/prometheus/web/ui/build_ui.sh .

# Fetch the exact pinned commit (not just branch tip) so a shallow clone can't
# silently land on the wrong sources.
RUN git init /build/prom-src && \
    git -C /build/prom-src remote add origin https://github.com/jacksontj/prometheus.git && \
    git -C /build/prom-src fetch --depth=1 origin ${PROM_FORK_COMMIT} && \
    git -C /build/prom-src checkout FETCH_HEAD

# Overlay workspace sources before npm install: the workspace dirs (mantine-ui/,
# module/) must exist when npm resolves them or workspace deps are skipped.
# The cache mount still reuses downloaded tarballs across builds.
RUN cp -r /build/prom-src/web/ui/mantine-ui ./mantine-ui && \
    cp -r /build/prom-src/web/ui/module     ./module

# --legacy-peer-deps: silences peer-dep conflicts from React 19 + older plugins.
RUN --mount=type=cache,target=/root/.npm \
    npm install --legacy-peer-deps

RUN bash build_ui.sh --build-module
RUN npm run build -w @prometheus-io/mantine-ui && \
    mkdir -p static && \
    rm -rf static/mantine-ui && \
    mv mantine-ui/dist static/mantine-ui

# Generate embed.go with builtinassets tag.  embed_stub.go (in vendor) also
# declares EmbedFS under this tag, so stage 2 removes it before compiling.
RUN printf '%s\n' \
  '// Code generated by Dockerfile ui-builder stage. DO NOT EDIT.' \
  '//' \
  '//go:build builtinassets' \
  '// +build builtinassets' \
  '' \
  'package ui' \
  '' \
  'import "embed"' \
  '' \
  '//go:embed static' \
  'var EmbedFS embed.FS' \
  > embed.go

# ── Stage 2: Build Go binaries ────────────────────────────────────────────────
FROM --platform=$BUILDPLATFORM golang:1.25-alpine3.21 AS builder

ARG BUILDPLATFORM
ARG TARGETARCH
ARG TARGETOS
ENV GOARCH=${TARGETARCH} GOOS=${TARGETOS}

WORKDIR /go/src/github.com/jacksontj/promxy

# Copy full source tree first (includes vendor/).
COPY go.mod go.sum ./
COPY . .

# Overlay built UI assets AFTER COPY . . so they win over vendor sources.
# Remove embed_stub.go: it and the generated embed.go both declare EmbedFS
# under builtinassets, so only one may exist.
COPY --from=ui-builder /build/webui/static \
     vendor/github.com/prometheus/prometheus/web/ui/static
COPY --from=ui-builder /build/webui/embed.go \
     vendor/github.com/prometheus/prometheus/web/ui/embed.go
RUN rm vendor/github.com/prometheus/prometheus/web/ui/embed_stub.go

RUN --mount=type=cache,target=/root/.cache/go-build \
    cd cmd/promxy && \
    CGO_ENABLED=0 go build -mod=vendor -tags netgo,builtinassets \
      -ldflags="-s -w"

RUN --mount=type=cache,target=/root/.cache/go-build \
    cd cmd/remote_write_exporter && \
    CGO_ENABLED=0 go build -mod=vendor \
      -ldflags="-s -w"

# ── Final image ───────────────────────────────────────────────────────────────
# Binaries are fully static (CGO_ENABLED=0, netgo); scratch is viable.
# /etc/passwd is inlined so USER nobody resolves at runtime.
FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/jacksontj/promxy/cmd/promxy/promxy               /bin/promxy
COPY --from=builder /go/src/github.com/jacksontj/promxy/cmd/remote_write_exporter/remote_write_exporter /bin/remote_write_exporter

# Minimal /etc/passwd so nobody (uid 65534) resolves inside scratch.
COPY --from=builder /etc/passwd /etc/passwd

LABEL org.opencontainers.image.authors="Thomas Jackson <jacksontj.89@gmail.com>"
EXPOSE 8082

USER nobody

ENTRYPOINT ["/bin/promxy"]
