ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
  hosts:
    - proxeus.example.com
  tls:
    - secretName: proxeus-tls
      hosts:
        - proxeus.example.com

config:
  proxeus:
    server_groups:
      - static_configs:
          - targets: ['thanos-query:9090']
