webConfig:
  existingSecret: proxeus-web-config

extraSecretMounts:
  - name: thanos-client-tls
    secretName: proxeus-thanos-client-tls
    mountPath: /etc/proxeus/secrets/thanos
    defaultMode: 0400
  - name: vm-bearer-token
    secretName: proxeus-vm-bearer-token
    mountPath: /etc/proxeus/secrets/vm

envFrom:
  - secretRef:
      name: proxeus-env

config:
  global:
    evaluation_interval: 5s
  proxeus:
    server_groups:
      - static_configs:
          - targets: ['thanos-query:9090']
        http_client:
          tls_config:
            ca_file: /etc/proxeus/secrets/thanos/ca.crt
            cert_file: /etc/proxeus/secrets/thanos/tls.crt
            key_file: /etc/proxeus/secrets/thanos/tls.key
      - static_configs:
          - targets: ['vmselect:8481']
        http_client:
          bearer_token_file: /etc/proxeus/secrets/vm/token
